//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmentUser
    {
        public int user_department_id { get; set; }
        public string user_id { get; set; }
        public int department_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
