//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDevice()
        {
            this.tblTokenQueues = new HashSet<tblTokenQueue>();
            this.tblDailyBreaks = new HashSet<tblDailyBreak>();
        }

        public int device_id { get; set; }
        public int department_id { get; set; }
        public string device_no { get; set; }
        public string location { get; set; }
        public string user_id { get; set; }
        public string device_name { get; set; }

        public string name
        {
            get
            {
                return device_name + " - " + device_no;
            }
        }


        public int is_active { get; set; }

        public virtual tblDepartment tblDepartment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTokenQueue> tblTokenQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDailyBreak> tblDailyBreaks { get; set; }
    }
}
