//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPlayList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlayList()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
        }

        [Key]
        public int playlist_id { get; set; }
        [Display(Name = "PlayList Name")]
        [Required]
        [StringLength(150)]
        public string playlist_name { get; set; }
        public int is_global { get; set; }
        public int is_active { get; set; }
        public int is_publish { get; set; }
        public string userId { get; set;}
        public string hometown { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
   
    }
}
