//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblScroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblScroll()
        {
            this.tblDepartments = new HashSet<tblDepartment>();
        }

        [Key]
        public int scroll_id { get; set; }
        public string content_en { get; set; }
        [Display(Name = "Content")]
        [Required]
        public string content_bn { get; set; }
        public int is_global { get; set; }
        public int is_active { get; set; }
        public int is_publish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        public virtual bool IsSelected{ get; set; }

    }
}
